name: build and publish docker image

on:
  push:
    branches:
      - "main"
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: Bardiche
    steps:
      - name: make env file
        shell: bash
        run:
          touch .env
          echo "TOKEN=${{ secrets.DISCORD_TOKEN }}" >> .env
      - name: checkout
        uses: actions/checkout@v3
      - name: setup docker buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0]

      - name: Login to Github Container Registry
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest